# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: DataDownloading

on:
  workflow_dispatch
  #schedule:
  #-  cron: '*/30 * * * *'  # At every 30th minute.

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    env:
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }} 
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} 

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install tm package
        run: Rscript -e 'install.packages("tm", dependencies = TRUE)'
      - name: Install tidytext package
        run: Rscript -e 'install.packages("tidytext", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install stringr package
        run: Rscript -e 'install.packages("stringr", dependencies = TRUE)'
      - name: Run The R Script
        run: Rscript DataDownloader.R
