# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: DataBroadcasting

on:
  #workflow_dispatch
  schedule:
  -  cron: '0 */6 * * *'  # At every 6th hour.

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    env:
      MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }} 
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} 
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install ggplot2 package
        run: Rscript -e 'install.packages("ggplot2", dependencies = TRUE)'
      - name: Install ggwordcloud package
        run: Rscript -e 'install.packages("ggwordcloud", dependencies = TRUE)'
      - name: Install RColorBrewer package
        run: Rscript -e 'install.packages("RColorBrewer", dependencies = TRUE)'
      - name: Run The R Script
        run: Rscript DataBroadcaster.R
